FROM --platform=linux/amd64 python:3.10-alpine as builder

RUN set -eux \
        && apk add --no-cache \
                gcc \
                musl-dev \
    && pip install --upgrade pip black[d]

EXPOSE 45484

ENTRYPOINT ["blackd", "--bind-host", "0.0.0.0", "--bind-port", "45484"]