"""Require Inventorys.name to be unique

Revision ID: 51e01761d5d6
Revises: 554263f2fb1d
Create Date: 2022-09-11 21:00:04.850672

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "51e01761d5d6"
down_revision = "554263f2fb1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inventory_name", table_name="inventory")
    op.create_index(op.f("ix_inventory_name"), "inventory", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_name"), table_name="inventory")
    op.create_index("ix_inventory_name", "inventory", ["name"], unique=False)
    # ### end Alembic commands ###
