"""Store default language for the User.

Revision ID: 554263f2fb1d
Revises: d50a24f51372
Create Date: 2022-08-20 15:00:55.317951

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "554263f2fb1d"
down_revision = "d50a24f51372"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("language", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "language")
    # ### end Alembic commands ###
