"""Create user model

Revision ID: d50a24f51372
Revises: d652442200cb
Create Date: 2022-08-07 20:58:04.137920

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d50a24f51372"
down_revision = "d652442200cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
