"""Drop item-inventory relationship.

Revision ID: d652442200cb
Revises: 7614e7b25fef
Create Date: 2022-06-18 20:49:06.648383

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d652442200cb"
down_revision = "7614e7b25fef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("item_inventory_id_fkey", "item", type_="foreignkey")
    op.drop_column("item", "inventory_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "inventory_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "item_inventory_id_fkey", "item", "inventory", ["inventory_id"], ["id"]
    )
    # ### end Alembic commands ###
